INSERT INTO kols (
    id, tenant_id, email, name, handle, primary_platform, stage, status,
    owner_user_id, last_inbound_at, last_outbound_at,
    agreed_price, agreed_platform, agreed_deadline, notes,
    type, external_profile_url, platform_handle, source,
    feishu_record_id, feishu_table_id, feishu_operator_name,
    last_feishu_synced_at, feishu_outreach_at, reply_resolved,
    created_at, updated_at, version
)
SELECT
    s.id,
    :'tenant_id'::uuid,
    s.email,
    s.name,
    s.handle,
    s.primary_platform::platform,
    s.stage::kol_stage,
    s.status::kol_status,
    s.owner_user_id,
    s.last_inbound_at,
    s.last_outbound_at,
    s.agreed_price,
    s.agreed_platform::platform,
    s.agreed_deadline,
    s.notes,
    s.type,
    s.external_profile_url,
    s.platform_handle,
    COALESCE(s.source, 'gmail'),
    s.feishu_record_id,
    s.feishu_table_id,
    COALESCE(s.feishu_operator_name, ''),
    s.last_feishu_synced_at,
    s.feishu_outreach_at,
    COALESCE(s.reply_resolved, false),
    COALESCE(s.created_at, now()),
    COALESCE(s.updated_at, s.created_at, now()),
    0
FROM dblink(
    :'source_dsn',
    $$
    SELECT id, email, name, handle, primary_platform::text, stage::text, status::text,
           owner_user_id, last_inbound_at, last_outbound_at,
           agreed_price, agreed_platform::text, agreed_deadline, notes,
           type, external_profile_url, platform_handle, source,
           feishu_record_id, feishu_table_id, feishu_operator_name,
           last_feishu_synced_at, feishu_outreach_at, reply_resolved,
           created_at, updated_at
    FROM public.kols
    $$
) AS s(
    id uuid,
    email text,
    name text,
    handle text,
    primary_platform text,
    stage text,
    status text,
    owner_user_id uuid,
    last_inbound_at timestamptz,
    last_outbound_at timestamptz,
    agreed_price numeric,
    agreed_platform text,
    agreed_deadline date,
    notes text,
    type text,
    external_profile_url text,
    platform_handle text,
    source text,
    feishu_record_id text,
    feishu_table_id text,
    feishu_operator_name text,
    last_feishu_synced_at timestamptz,
    feishu_outreach_at date,
    reply_resolved boolean,
    created_at timestamptz,
    updated_at timestamptz
)
ON CONFLICT (id) DO NOTHING;
