INSERT INTO emails (
    id, tenant_id, gmail_message_id, gmail_thread_id, kol_id, user_id, template_id,
    direction, from_email, to_emails, cc_emails, subject,
    body_text, body_html, body_zh, attachment_names, has_attachments, sent_at,
    ai_stage_signal, ai_priority, ai_summary, ai_extracted_fields,
    ai_suggested_action, ai_error, ai_processed_at,
    is_read, read_at, read_by, created_at, updated_at, version
)
SELECT
    s.id,
    :'tenant_id'::uuid,
    s.gmail_message_id,
    s.gmail_thread_id,
    s.kol_id,
    s.user_id,
    s.template_id,
    s.direction::email_direction,
    s.from_email,
    s.to_emails,
    s.cc_emails,
    s.subject,
    s.body_text,
    s.body_html,
    s.body_zh,
    COALESCE(s.attachment_names, '{}'),
    COALESCE(s.has_attachments, false),
    s.sent_at,
    s.ai_stage_signal::kol_stage,
    s.ai_priority,
    s.ai_summary,
    COALESCE(s.ai_extracted_fields, '{}'::jsonb),
    s.ai_suggested_action,
    s.ai_error,
    s.ai_processed_at,
    COALESCE(s.is_read, false),
    s.read_at,
    s.read_by,
    COALESCE(s.created_at, now()),
    COALESCE(s.created_at, now()),
    0
FROM dblink(
    :'source_dsn',
    $$
    SELECT id, gmail_message_id, gmail_thread_id, kol_id, user_id, template_id,
           direction::text, from_email, to_emails, cc_emails, subject,
           body_text, body_html, body_zh, attachment_names, has_attachments, sent_at,
           ai_stage_signal::text, ai_priority, ai_summary, ai_extracted_fields,
           ai_suggested_action, ai_error, ai_processed_at,
           is_read, read_at, read_by, created_at
    FROM public.emails
    $$
) AS s(
    id uuid,
    gmail_message_id text,
    gmail_thread_id text,
    kol_id uuid,
    user_id uuid,
    template_id uuid,
    direction text,
    from_email text,
    to_emails text[],
    cc_emails text[],
    subject text,
    body_text text,
    body_html text,
    body_zh text,
    attachment_names text[],
    has_attachments boolean,
    sent_at timestamptz,
    ai_stage_signal text,
    ai_priority text,
    ai_summary text,
    ai_extracted_fields jsonb,
    ai_suggested_action text,
    ai_error text,
    ai_processed_at timestamptz,
    is_read boolean,
    read_at timestamptz,
    read_by uuid,
    created_at timestamptz
)
ON CONFLICT (id) DO NOTHING;
